name: Build

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set lower case owner name and repo name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push conatiner
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
      - uses: actions/checkout@master
      - name: Build and push volume container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./volume_container/Dockerfile
          push: true
          tags: ghcr.io/vc_${{ github.repository }}:latest,ghcr.io/vc_${{ github.repository }}:${{ github.sha }}
      - uses: actions/checkout@master
