name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_name: [esp32AIThinker]
        target_build_type: ["", _release, _OTA]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: test-image:latest
          push: false
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /ESP
            export OPENIRIS_CI_BUILD=1
            mkdir build 
            mkdir build/${{ matrix.target_name }}${{ matrix.target_build_type }}
            echo "::group::pio run"
            pio run --environment ${{ matrix.target_name }}${{ matrix.target_build_type }}
            echo "::endgroup::"
            unzip -l './build/${{ matrix.target_name }}${{ matrix.target_build_type }}/*.zip'
      - name: Verify build
        run: |
          ls -l ./build/${{ matrix.target_name }}${{ matrix.target_build_type }}
