name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_name: [esp32AIThinker, esp32M5Stack, esp32Cam, esp_eye, wrover]
        target_build_type: ["", _release, _OTA]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: ./Dockerfile
          options: --rm \
            --mount type=bind,source="${{ github.workspace }}",target=/workspace \
            -u `id -u $USER`:`id -g $USER`
          run: |
            cd /OpenIris/ESP
            export OPENIRIS_CI_BUILD=1
            mkdir build 
            mkdir build/${{ matrix.target_name }}${{ matrix.target_build_type }}
            echo "::group::pio run"
            pio run --environment ${{ matrix.target_name }}${{ matrix.target_build_type }}
            echo "::endgroup::"
            unzip -l './build/${{ matrix.target_name }}${{ matrix.target_build_type }}/*.zip'
      - name: Verify build
        run: |
          ls -l ./build/${{ matrix.target_name }}${{ matrix.target_build_type }}
